services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - stockolm-net

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    # volumes:
    #   - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - stockolm-net

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      ***REMOVED***
      ***REMOVED***
      ***REMOVED***
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      ***REMOVED***
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stockolm-net

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    restart: always
    networks:
      - stockolm-net

networks:
  stockolm-net:
    driver: bridge

volumes:
  postgres-data: