services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    networks:
      - stockolm-net

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    # volumes:
    #   - ./backend:/app  
    networks:
      - stockolm-net

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    restart: always
    networks:
      - stockolm-net

networks:
  stockolm-net:
    driver: bridge